# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexander Viftrup Andersen
title: Security Systems Engineer
email: alex@viftrup.eu
website: 

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  viftrup
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Welcome to my <mark>127.0.0.1</mark>
about_profile_image: images/viftrup.jpg
about_content: | # this will include new lines to allow paragraphs
  My name's Alexander and I'm a Security Network Consultant and this is my simplified LinkedIn-resumé-front-page.  
  <br><br>

  My key competences is: <mark>Security</mark> and <mark>Firewalls</mark>  

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left            
        title: Conscia
        # link_text: boringcompany.com
        sub_title: Security Systems Engineer
        caption: June 2022 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Network consultant working primarily with security solutions - primarily focused on Cisco products, but also getting into Palo Alto security suite.
            
            Especially comptent within Cisco firewalling products, such as Cisco ASA and Cisco Firepower.


      - layout: left            
        title: Netteam
        # link_text: boringcompany.com
        sub_title: Security Systems Engineer
        caption: Sep 2020 - June 2022
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Network consultant working primarily with security solutions - primarily focused on Cisco products.
            
            Especially comptent within Cisco firewalling products, such as Cisco ASA and Cisco Firepower.


      - layout: left            
        title: Siemens Gamesa Renewable Energy
        # link_text: boringcompany.com
        sub_title: OT Cyber Security Architect
        caption: Dec 2019 - Sep 2020
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Helping the company to mature their cyber security footprint and being complaint within standards like NERC-CIP and ISO-27001.
            

      - layout: left            
        title: Siemens Gamesa Renewable Energy
        # link_text: boringcompany.com
        sub_title: SCADA Network Specialist
        caption: Feb 2019 - Jan 2020
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Solving *"network-issues"* by fixing misconfigured servers.
            
            Traveled a lot throughout the world to provide training for regional colleges and on-site troubleshooting/replacement of equipment.
            
      - layout: left      
        title: Siemens Wind Power
        # link_text: boringcompany.com
        sub_title: Data Technician Apprentice
        caption: Mar 2016 - Feb 2019 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Worked in the Diagnostic Center at Brande providing 3rd level support for network and SCADA systems world-wide.
            

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cisco
        caption: 2010 - 2013
        sub_title: CCNA
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

 #     Look at this cool image  
 #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
